train_list: '/Data/luy8/glomeruli/skin/json/trainset3.json'

val_list: '/Data/luy8/glomeruli/skin/json/fold1.json'

test_list: '/Data/luy8/glomeruli/skin/json/fold2.json'

output_csv_dir: '/Data/luy8/glomeruli/exp_results/config_ham'

dataset: 'ham'

num_classes: 7

epochs: 60

start_epoch: 0

batch_size: 16

lr: 0.001

network: 105

num_workers: 4

beta: 1

cutmix_prob: 0

circlemix_prob: 0