train_list: '/Data/luy8/centermix/json/trainset3_os.json'

val_list: '/Data/luy8/centermix/json/fold1.json'

test_list: '/Data/luy8/centermix/json/fold2.json'

output_csv_dir: '/Data/luy8/centermix/exp_results'

supervised: True # True means use simple supervised method

num_classes: 2

epochs: 20

start_epoch: 0

batch_size: 8

lr: 0.0001

## Checkpoints
resume: ''

## Miscs
manualSeed: 0

##Device options
gpu: '0'

##Method options
n_labeled: 385

val_iteration: 385

out: 'result'

alpha: 0.75

lambda_u: 75

T: 0.5

ema_decay: 0.999

network: 103

num_workers: 4

aggregate: 'True'

aug: 'None'

circle: 'None'

mode: 'None'

beta: 1

cutmix_prob: 1

centermix_prob: 0