train_list: '/Data/luy8/centermix/renal/json/c3_trainset5_us.json'

val_list: '/Data/luy8/centermix/renal/json/c3_fold3_us.json'

test_list: '/Data/luy8/centermix/renal/json/c3_fold4_us.json'

output_csv_dir: '/Data/luy8/centermix/exp_results/config_renal'

supervised: True # True means use simple supervised method

c5_pretrained: True

num_classes: 3

epochs: 60

start_epoch: 0

batch_size: 16

lr: 0.001

optimizer: 'SGD'

## Checkpoints
resume: ''

## Miscs
manualSeed: 0

##Device options
gpu: '0'

network: 105

num_workers: 4

aug: 'True'

mode: 'None'

beta: 1

cutmix_prob: 0

centermix_prob: 0