train_list: '/Data/luy8/centermix/renal/json/binary_trainset5_us.json'

val_list: '/Data/luy8/centermix/renal/json/binary_fold3_us.json'

test_list: '/Data/luy8/centermix/renal/json/binary_fold4_us.json'

output_csv_dir: '/Data/luy8/centermix/exp_results/config_renal'

supervised: True # True means use simple supervised method

c5_pretrained: False

num_classes: 2

epochs: 40

start_epoch: 0

batch_size: 16

lr: 0.01

optimizer: 'SGD'

## Checkpoints
resume: ''

## Miscs
manualSeed: 0

##Device options
gpu: '0'

network: 105

num_workers: 4

aggregate: 'None'

aug: 'True'

beta: 1

cutmix_prob: 1

centermix_prob: 0