train_list: '/Data/luy8/centermix/ham-10000/json/trainset3.json'

val_list: '/Data/luy8/centermix/ham-10000/json/fold1.json'

test_list: '/Data/luy8/centermix/ham-10000/json/fold2.json'

output_csv_dir: '/Data/luy8/centermix/exp_results/config_ham'

num_classes: 7

epochs: 90

start_epoch: 0

batch_size: 32

lr: 0.01

optimizer: 'SGD'

network: 105

num_workers: 4

beta: 1

cutmix_prob: 1

centermix_prob: 0