train_list: '../renal/json/all/trainset5.json'

val_list: '../renal/json/all/fold3.json'

test_list: '../renal/json/all/fold4.json'

ext_test_list: '../renal/json/all/test.json'

output_csv_dir: '../exp_results/config_renal'

dataset: 'renal'

num_classes: 5

epochs: 60

start_epoch: 0

batch_size: 16

lr: 0.01

network: 105

num_workers: 4

beta: 1

cutmix_prob: 1

circlemix_prob: 0

cutout_prob: 0